### ISSUE TITLE
Page "Configuration des services"

### ISSUE THREAD

**Issue by SamuelAllain** [InseeFrLab/docs.sspcloud.fr#12]
Bonjour,
Je trouverais ça très précieux d'avoir une page "Configuration des services" sous "Lancer un projet R avec le datalab" avec une partie par onglet  (S3, Kubernetes, Init...). Plusieurs paramètres n'étaient pas explicites pour moi : 

+ **partager le service** : case attirante mais que j'avais mal comprise. Les infos de Romain me semblent assez importantes pour figurer dans la doc : "la création de groupes se fait de notre côté sur demande (nom de groupe + usernames des membres + besoin ou non d'un espace de stockage associé sur MinIO), sur Tchap (en privé) ou par mail à l'adresse [innovation@insee.fr](mailto:innovation@insee.fr). La notion de partage de service n'existe que dans le cadre d'un groupe, et une fois que le groupe est créé elle est assez simple : il suffit de cocher la case correspondante à l'ouverture du service et les autres membres verront le service et pourront l'utiliser"
+ **Init** : je croyais qu'il fallait mettre du bash directement dans le champ. Et aussi rappeler que le script est exécuté en root et que cela peut générer des problèmes. Un exemple de script d'Init serait très utile, j'ai passé des heures à construire [le mien](https://git.drees.fr/drees_code_public/ressources/tutos/-/blob/diffusion/contenu/init.sh)
+ **networking**
+ **security**

Qu'en pensez-vous ?

**Comment by garronej** [comment]
J'en pense du bien.
