### ISSUE TITLE
Not able to deploy forked repo

### ISSUE THREAD

**Issue by nashugame** [InseeFrLab/docs.sspcloud.fr#18]
Hello,
I am facing error while hosting the repo on github pages. I need some help regarding it. I have already added the verified domain name etc.
![Screenshot from 2023-06-22 10-41-09](https://github.com/InseeFrLab/docs.sspcloud.fr/assets/34041404/92753167-5821-482f-8f83-373358f2caa1)

**Comment by garronej** [comment]
Hi @nashugame,  

What website are you trying to deploy?  
https://docs.sspcloud.fr/
or 
https://www.sspcloud.fr/  

?

**Comment by nashugame** [comment]
Hi @garronej ,
Its https://docs.sspcloud.fr/ via github pages

**Comment by garronej** [comment]
Unfortunately, you can't.  
It's a GitBook website:  https://www.gitbook.com/  

You can sync your fork with Gitbook and deploy using it.

**Comment by nashugame** [comment]
Hi,
I know it's created with Gitbook, I already have mine insync with gitbook. The changes done in gitbook is being correctly reflected in my repo. The problem I'm facing is with the deployment. I have shared the screenshot of error in my github actions for reference

**Comment by garronej** [comment]
You can't self host a GitBook website.  
Theses are just the Markdwons. If you want to deploy the website you have to do it via GitBook.  

Jekill is unable to generate a statical website from GitBook markdown.
