### ISSUE TITLE
404 link in version-control.html

### ISSUE THREAD

**Issue by scenaristeur** [InseeFrLab/docs.sspcloud.fr#25]
Bonjour, 
sur cette page https://inseefrlab.github.io/docs.sspcloud.fr/docs/fr/version-control.html le lien vers "Python ce chapitre de cours " envoie vers une 404 https://pythonds.linogaliana.fr/course/git/
idem pour le lien dans "l’espace formation du Datalab."

le bon lien  pour le cours python / git semble être https://pythonds.linogaliana.fr/content/git/exogit.html

et pour R https://inseefrlab.github.io/formation-bonnes-pratiques-git-R/

**Comment by avouacr** [comment]
Thank's, fixed in 2af6aff032be6d9aeb638bd86c8ec6394e93dc09
