### ISSUE TITLE
Access denied for the video in the newsletter "introduction au MLOps presentation de ML Flow"

### ISSUE THREAD

**Issue by PhilippeGalvan** [InseeFrLab/docs.sspcloud.fr#7]
The following link https://minio.lab.sspcloud.fr/f7sggu/diffusion/20210422\_MLOps\_MLflow.mp4 in `docs/actualites/introduction-au-mlops-presentation-de-ml-flow.md` (https://docs.sspcloud.fr/actualites/introduction-au-mlops-presentation-de-ml-flow) returns access denied:

```XML
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>diffusion/20210422_MLOps_MLflow.mp4</Key>
<BucketName>f7sggu</BucketName>
<Resource>/f7sggu/diffusion/20210422_MLOps_MLflow.mp4</Resource>
<RequestId>16B463EC6C5C70B6</RequestId>
<HostId>4bbd43eb-e483-425a-b62e-3968e392aa17</HostId>
</Error>
```

It looks like it is the case for other videos in the `actualites` section.

**Comment by RLesur** [comment]
Hi @PhilippeGalvan,

Thanks a lot for the report!
I'm the owner of the `f7sggu` bucket. I don't know why but my public files have been turned out.
This is now fixed.
