### ISSUE TITLE
A few typos in onyxia-guide/controle-de-version-avec-git.md

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/docs.sspcloud.fr#8]
Just reporting 3 minor typos in the documentation page on git:

- l'utilisateur **peur** partager ses modifications => peut
- la synchronisation de la copie **local** d'un projet => locale
- utile de se **familliariser** avec l'usage de Git => familiariser

**Comment by avouacr** [comment]
@fBedecarrats thank you, typos fixed
