### ISSUE TITLE
Feature request: indicate in the documentation how to start jupyter/Rstudio in the right notebook/project respectively

### ISSUE THREAD

**Issue by fBedecarrats** [InseeFrLab/docs.sspcloud.fr#9]
Hello,
The methods to start the jupyter or Rstudio sessions from the intended place are not trivial. The solutions have been found in  formation-spark/init-notebook.sh  for Jupyter:
```py
# Open a given notebook when starting Jupyter Lab
[ -z "$IPYNB_PATH" ] || echo "c.LabApp.default_url = '/lab/tree/${REPO}/${IPYNB_PATH%.*}/${IPYNB_PATH}'" >> /home/jovyan/.jupyter/jupyter_server_config.py
```
and in utilitR/init_utilitr.sh for RStudio:
```r
# Open the project
    echo \
    "
    setHook('rstudio.sessionInit', function(newSession) {
        if (newSession && identical(getwd(), path.expand('~')))
        {
            message('Ouverture du tutoriel')
            rstudioapi::openProject('~/utilitr')
            }
            }, action = 'append')
            " >> /home/rstudio/.Rprofile
```

I spent unsuccessful  hours trying to figure out the latter myself before finding @linogaliana's solution. I suggest that these methods be added to the documentation to help future users in the same situation.
Thanks again for this wonderful tool!

**Comment by avouacr** [comment]
HI @fBedecarrats,

I agree these commands are not obvious, I also spent several hours trying to derive the Jupyter one from the doc before finding the solution you mention. To answer your question, I was planning to produce basic training templates for R and Python for people interested in doing their training programs on the SSP Cloud, and @garronej already has effective solutions for this purpose, so it should be available soon.

**Comment by avouacr** [comment]
We documented such usage in our [sspcloud-init-scripts](https://github.com/InseeFrLab/sspcloud-init-scripts) repository.
